name: ft_transcendence
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=transcendence
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST_AUTH_METHOD=trust # Add this line to allow easier connections
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - transcendence
    volumes:
      - pgdata:/var/lib/postgresql/data # Changed volume mount point

  cloudbeaver:
    image: dbeaver/cloudbeaver
    container_name: dbeaver
    restart: always
    ports:
      - "9090:8978"
    # volumes:
    #   - cloudbeaver_data:/opt/cloudbeaver/workspace
    environment:
      - CB_CONNECT_HOST=0.0.0.0 # Allow connections from any host
    networks:
      - transcendence
    depends_on:
      - db

networks:
  transcendence:

volumes:
  pgdata:
  #   name: pgdata
  #   driver: local
  #   driver_opts:
  #     device: /home/mhaan/goinfre/ft_transcendence/db_data
  #     type: none
  #     o: bind
  # cloudbeaver_data:
  #   name: cloudbeaver_data
  #   driver: local
